# Generated by Django 3.2.16 on 2025-03-01 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Уникальное название категории, не более 256 символов', max_length=256, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание категории', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Слаг категории', unique=True, verbose_name='Слаг')),
                ('is_published', models.BooleanField(default=True, help_text='Статья опубликована', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(help_text='Дата создания поста', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название места', max_length=256, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Место опубликовано', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(help_text='Дата создания места', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Уникальное название категории, не более 256 символов', max_length=256, verbose_name='Название')),
                ('text', models.TextField(help_text='Текст поста', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(help_text='Дата публикации поста', verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, help_text='Статья опубликована', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(help_text='Дата создания поста', verbose_name='Дата создания')),
                ('author', models.ForeignKey(help_text='Автор поста', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, help_text='Категория поста', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
                ('location', models.ForeignKey(blank=True, help_text='Местоположение поста', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
